# Error Boundaries
> * Trong qúa khứ JS error bên trong mỗi components phá vỡ trạng thái bên trong của React state và gây ra cho nó những lỗi khó hiểu khi render những lần tiếp theo.
> * Những lỗi này luôn luôn bị gây ra bởi 1 lỗi trước trong code, nhưng React không cung cấp cách để xử lý chúng một cách hiệu quả trong components và cũng không thể phục hồi chúng

## Introducing Error Boundaries
Một lỗi trong UI thì không nên break cả app. Để giải quyết vấn đề này thì React 16 giới thiệu 1 nội dung là "error boundary"

> Chú ý EB không bắt được lỗi cho:
> - Event handlers
> - Asynchronous code
> - Server side rendring

Một class component trở thành error boundary nếu nó định nghĩa 1 trong 2 hoặc cả 2 method static **getDerivedStateFromError()** hay **componentDidCatch()**

```jsx
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // Update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // You can also log the error to an error reporting service
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children; 
  }
}
<ErrorBoundary>
  <MyWidget />
</ErrorBoundary>
```
chỉ bắt được lỗi dưới nó. Còn lỗi trong chính nó thì cũng không bắt được

## Nơi đặt Error Boundaries
Mức độ chi tiết của lỗi thì phụ thuộc vào bạn. 

## Cách để xử lý cách lỗi không bắt được
Khi mà xảy ra lỗi không bắt được thì nó sẽ không render ra component tree. Điều này thì tốt hơn là hiển thị thông tin sai lầm

## Component stack Traces
React 16 in tất cả các lỗi trong suốt quá trình rendering tới console. Ngoài lời nhắn thông báo lỗi nó cũng cung cấp truy vết

## Thế còn try/catch
try/catch thì tốt nhưng nó chỉ được sử dụng trong những đoạn code bắt buộc
```jsx
try {
  showButton();
} catch (error) {
  // ...
}
```

## Event Handler
```jsx
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    try {
      // Do something that could throw
    } catch (error) {
      this.setState({ error });
    }
  }

  render() {
    if (this.state.error) {
      return <h1>Caught an error.</h1>
    }
    return <button onClick={this.handleClick}>Click Me</button>
  }
}
```